// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//

using System.Collections.Generic;

namespace Models {

	public class KeyCollection
	{
		public List<Product_Key> Product_Keys {get; set;}
	}
	public class Product_Key
	{
		public string Name { get; set; }
		public List<Key> Keys { get; set; }

	}
	public class Key
	{
		public string ID { get; set; }
		public string Type { get; set; }
		public string ClaimedDate { get; set; }
		public string Value { get; set; }
    }
    
}
